FLEXSDK-1617: skip validate version

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -54,12 +54,12 @@ jobs:
           echo "version=$version" >> $GITHUB_OUTPUT
           echo "Extracted version: $version"
 
-      - name: Validate version
-        run: |
-          VERSION=${{ steps.extract-version.outputs.version }}
-          echo "Releasing version: $VERSION"
-          # Fail if version already exists in npm registry
-          npm view twilio-taskrouter@$VERSION version --registry https://registry.npmjs.org && exit 1 || true
+      # - name: Validate version
+      #   run: |
+      #     VERSION=${{ steps.extract-version.outputs.version }}
+      #     echo "Releasing version: $VERSION"
+      #     # Fail if version already exists in npm registry
+      #     npm view twilio-taskrouter@$VERSION version --registry https://registry.npmjs.org && exit 1 || true
       - name: Install and Build twilio-taskrouter
         run: yarn install && yarn run build
       - name: Upload Build Artifacts
